version: "3"
services:
  webserver:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8008:80"
    volumes:
      - ./scripts:/var/www/html
      - ./phpfiles:/var/www/phpfiles
      - ./apache/logs:/var/log/apache2
    depends_on:
      - "bbdd"

  bbdd:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: iaw_db
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PORT: 3306
    volumes:
      - ./.db_data:/var/lib/mysql
      - ./mysql/:/docker-entrypoint-initdb.d
      - ./datos:/datos
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: "bbdd"
      PMA_USER: "root"
      PMA_PASSWORD: "secret"
    depends_on:
      - "bbdd"
    ports:
      - "8080:80"
